# Generated by Django 6.0.7 on 2026-07-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_borrowing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="money_to_pay",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
