# Generated by Django 6.0.7 on 2026-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_payment_money_to_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "PENDING"), ("paid", "PAID")],
                default="pending",
                max_length=7,
            ),
        ),
    ]
