# Generated by Django 6.0.7 on 2026-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("payment", "PAYMENT"), ("fine", "FINE")],
                default="payment",
                max_length=7,
            ),
        ),
    ]
