# Generated by Django 6.0.7 on 2026-07-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=255),
        ),
    ]
