# Generated by Django 6.0.7 on 2026-07-28 21:20

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=book.models.upload_image_to
            ),
        ),
    ]
